/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zl_myfirstndk_NdkJniUtils */

#ifndef _Included_com_example_zl_myfirstndk_NdkJniUtils
#define _Included_com_example_zl_myfirstndk_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zl_myfirstndk_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zl_myfirstndk_NdkJniUtils_getCLanguageString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zl_myfirstndk_NdkJniUtils
 * Method:    f
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zl_myfirstndk_NdkJniUtils_f
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
